apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kvrocks-cluster.fullname" . }}-config
  labels:
    {{- include "kvrocks-cluster.labels" . | nindent 4 }}
data:
  kvrocks.conf: |
    bind {{ .Values.kvrocksConfig.bind }}
    port {{ .Values.kvrocksConfig.port }}
    cluster-enabled {{ .Values.kvrocksConfig.cluster_enabled }}
    requirepass __KVR_PASSWORD__
    masterauth __KVR_PASSWORD__
    dir {{ .Values.kvrocksConfig.dir }}
    rocksdb.write_buffer_size {{ .Values.kvrocksConfig.rocksdb_write_buffer_size }}
    rocksdb.max_write_buffer_number {{ .Values.kvrocksConfig.rocksdb_max_write_buffer_number }}
    rocksdb.target_file_size_base {{ .Values.kvrocksConfig.rocksdb_target_file_size_base }}
    rocksdb.max_background_compactions {{ .Values.kvrocksConfig.rocksdb_max_background_compactions }}
    rocksdb.max_background_flushes {{ .Values.kvrocksConfig.rocksdb_max_background_flushes }}
