{{- if not .Values.auth.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kvrocks-cluster.fullname" . }}-password
  labels:
    {{- include "kvrocks-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.auth.password | quote }}
{{- end }}
